name: Node.js CI

on:
  push:
    branches: [ Auth-CI ]
  pull_request:
    branches: [ Auth-CI ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
        cache-dependency-path: Auth
    - name: Build db_middleware with npm    
      working-directory: ./Auth 
    - run: npm install
    - run: npm test



